### ISSUE TITLE
C1: As a user, I want to be able to share access to a space or individual plants with other users, so that they can also view the required tasks and status of plants.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#12]
## Acceptance Criteria

- [x] Given a spaces has been created, the owner can add users who are not already members of the space.
- [x] Given a space has been created and a user has been added as member to this space, the use can be removed from the space.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#15
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#16

### Backend

- [x] #51

**Comment by NorDar** [comment]
Already implemented for plants, spaces are open.

**Comment by Danielgergely** [comment]
Went with a different implementation. Users are added to spaces by the owners. No invites and QR-codes. Otherwise working
