### ISSUE TITLE
N1: As a plant owner, I want to receive a notification if another user did not take care of their tasks, so that I can remind them or do it myself.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#15]
## Acceptance Criteria

- [x] Given responsibilities are assigned, when any of the responsible people do not mark their task as done in a certain time period, the owner of the plant is notified, so that the task does not remain not done.

### Frontend

- No implementation needed

### Backend

- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #113
- [x] #120
- [x] #123

**Comment by NorDar** [comment]
Mails sent via Mailjet End up in SPAM because SPF and DKIM are not set up and we try to send from an  @uzh.ch domain.
- [ ] Fix emails land in Spam.
