### ISSUE TITLE
Set up user service

### ISSUE THREAD

**Issue by M-Sigg** [sopra-fs24-group-01/sopra-fs24-plantparent-server#35]

**Comment by Danielgergely** [comment]
Please add a get user by username endpoint. (During login, the user will provide his/her username and password, which we should then use to authenticate, and return the user to the frontend)

**Comment by M-Sigg** [comment]
> Please add a get user by username endpoint. (During login, the user will provide his/her username and password, which we should then use to authenticate, and return the user to the frontend)

This will be addressed in other issue, specifically #40 and #60 when we implement the backend login functionalities. I am currently working on this, should be done today
