### ISSUE TITLE
Create REST API for editing plants

### ISSUE THREAD

**Issue by M-Sigg** [sopra-fs24-group-01/sopra-fs24-plantparent-server#49]

**Comment by NorDar** [comment]
Already included the functionality for this with a91549a9771acb9cde2627bf6b789f1c4779c333 
Tests available here:
https://github.com/sopra-fs24-group-01/sopra-fs24-plantparent-server/commit/a91549a9771acb9cde2627bf6b789f1c4779c333#diff-7ded298a3e3e69d6a0981cea2e38653c0f026a50e49bcf413739a0f5d85ca3c3R198-R231
