### ISSUE TITLE
Search for email API

### ISSUE THREAD

**Issue by M-Sigg** [sopra-fs24-group-01/sopra-fs24-plantparent-server#55]

**Comment by geringproduktiv** [comment]
# 1. [Gmail API](https://developers.google.com/gmail/api/guides)
- Free
- API Limit: 250 quota units per user per second, moving average (allows short bursts)
- Method Limit (messages.send): 100 quota units

# 2. [Sendgrid](https://sendgrid.com/en-us/solutions/email-api)
- Free trial available
- API Limit: 600 requests per minute

# 3. [Mailjet](https://www.mailjet.com/products/email-api/)
- Free trial available
- API Limit: 6000 Mails/month; 200 Mails/day
- Rest of mails are put in queue and sent out next day

# 4. [Mailgun](https://www.mailgun.com/)
- Free trial available
- API Limit: 5000 Mails/month

**Comment by NorDar** [comment]
* Mailgun is free 30 days then 35/month

**Comment by NorDar** [comment]
* mailjet is free 30 days then 15/month
