### ISSUE TITLE
Configure email API

### ISSUE THREAD

**Issue by M-Sigg** [sopra-fs24-group-01/sopra-fs24-plantparent-server#56]

**Comment by NorDar** [comment]
* Mailjet account created under my uzh mail.
* API Documentation: https://dev.mailjet.com/email/reference/ 
  *  https://dev.mailjet.com/email/reference/send-emails#v3_1_post_send

**Comment by NorDar** [comment]
Store mailjet secrets in google secret manager of server project

https://console.cloud.google.com/security/secret-manager?project=sopra-fs24-group-01-server

As:
* mailjet-public-key
* mailjet-private-key

**Comment by NorDar** [comment]
Mails can be sent via POST to: `https://api.mailjet.com/v3.1/send`

Authentication is BASIC, username/password correspond to `MJ_PUBLIC_KEY` and `MJ_PRIVATE_KEY`

Header need to be set:
`Content-Type`: `application/json`

Body: 
```json
{
      "SandboxMode":false,
      "Messages":[
        {
          "From":
            {
              "Email":"nordinbensalem.dari@uzh.ch",
              "Name":"Groot root @PlantParent"
            }
          ,
          "Subject":"You have plants that need attention!",
          "TextPart":"Your plants thirsty plant, very-thirsty-plant need watering.",
          "To":[
            {
              "Email":"nordinbensalem.dari@uzh.ch"
            }
          ]
        }
      ]
	}
```
