### ISSUE TITLE
P3: As a plant owner, I want to be able to create a caring schedule for a plant, so that the plant receives the care it needs.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#6]
## Acceptance Criteria

- [x] Given a plant is created, when clicking on a plant, then the plant details are displayed.
- [x] Given the plant details are displayed, when the user clicks on the ‘create caring schedule’ button, the ‘caring schedule’ page is displayed.
- [x] Given the user filled in the required caring data, when the user clicks ‘save schedule’, the schedule is created and the user is redirected to the plant page, where the scheduling information is displayed.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#21
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#22

### Backend

- [x] #49
- [x] #50

**Comment by NorDar** [comment]
* For my existing plant I can click on the plants name to see the details page
* When clicking the caring schedule button I can set the watering and caring information
* Confirming the schedule the user is redirected to the plant overview where the data is shown
