### ISSUE TITLE
P4: As a user, I want to see all upcoming tasks, so I can plan ahead and don't forget.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#7]
## Acceptance Criteria
- [x] Given the user is on the main page, when viewing the displayed plants, next watering/caring schedules are displayed. 
- [x] Given the user is on the main page, when clicking on a plant, the user is redirected to the plant detail page, where the planned schedule is displayed.

### Frontend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#19
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-client#20

### Backend

-

**Comment by NorDar** [comment]
* On the main page the plant status is shown. Days overdue and in how many days an action needs to be applied.
* Opening the plant the details of the schedule is shown
