### ISSUE TITLE
P5: As a plant owner, I want to be able to edit existing schedules for my plants, so that I can adjust them if needed.

### ISSUE THREAD

**Issue by geringproduktiv** [sopra-fs24-group-01/sopra-fs24-plantparent-server#8]
## Acceptance Criteria

- [ ] Given that a care schedule for a plant is already created, the schedule should be displayed.
- [ ] Given the schedule is displayed, an ‘edit schedule’ button is displayed that brings the user into an edit mode
- [ ] Given the user has entered edit mode, the option to save or discard changes is displayed and after clicking them the user is redirected to the schedule overview.

### Frontend

- Has already been implemented.

### Backend

- [x] sopra-fs24-group-01/sopra-fs24-plantparent-server#77

**Comment by NorDar** [comment]
Changes for this have been implemented in 71a4cb66908fc6589eeb255d86ded3b764d57454
